version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stats-server/
    image: breannly/ewm-stats-server
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/enw-stats
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DB=enw-stats

  stats-db:
    image: postgres:14-alpine
    container_name: enw-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enw-stats
    volumes:
      - .:/docker-entrypoint-initdb.d

  ewm-service:
    ports:
      - "8080:8080"
    build: ewm-service/
    image: breannly/ewm-main-service
    container_name: ewm-main-service
    depends_on:
        - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/enw-main-service
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - POSTGRES_DB=enw_main_service
      - EXPLORE_WITH_ME_STATS_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: enw-main-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=enw-main-service
    volumes:
      - .:/docker-entrypoint-initdb.d
