CREATE TABLE IF NOT EXISTS VIEWS
(
    view_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app     VARCHAR(100),
    uri     VARCHAR(100),
    ip      VARCHAR(100),
    "timestamp" TIMESTAMP,
    CONSTRAINT view_pk PRIMARY KEY (view_id)
);